# Generated by Django 3.2.7 on 2021-09-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_projects_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
