# Generated by Django 3.2.7 on 2021-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20210911_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issues',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
