# Generated by Django 3.2.7 on 2021-09-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210913_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
