# Generated by Django 3.2.7 on 2021-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_issues_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('faible', 'faible'), ('moyenne', 'moyenne'), ('élevée', 'élevée')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('à faire', 'à faire'), ('en cours', 'en cours'), ('terminé', 'terminé')], default='à faire', max_length=128),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('amélioration', 'amélioration'), ('tâche', 'tâche')], max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('ios', 'ios'), ('android', 'android')], max_length=128),
        ),
    ]
